language: python
python:
- '2.7'
before_install:
- sudo mkdir -p /downloads
- sudo chmod a+rw /downloads
- curl -L http://sourceforge.net/projects/pyqt/files/sip/sip-4.16.5/sip-4.16.5.tar.gz
  -o /downloads/sip.tar.gz
- curl -L http://sourceforge.net/projects/pyqt/files/PyQt4/PyQt-4.11.3/PyQt-x11-gpl-4.11.3.tar.gz
  -o /downloads/pyqt4.tar.gz
- sudo mkdir -p /builds
- sudo chmod a+rw /builds
install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sudo apt-get install -y libqt4-dev
- sudo apt-get install -y mesa-common-dev libgl1-mesa-dev libglu1-mesa-dev
- pushd /builds
- tar xzf /downloads/sip.tar.gz --keep-newer-files
- pushd sip-4.16.5
- python configure.py
- make
- sudo make install
- popd
- tar xzf /downloads/pyqt4.tar.gz --keep-newer-files
- pushd PyQt-x11-gpl-4.11.3
- python configure.py -c --confirm-license --no-designer-plugin -e QtCore -e QtGui
  -e QtTest
- make
- sudo make install
- popd
- popd
- pip install -r requirements.txt
- pip install pyinstaller
script:
- python -m unittest discover tests
after_success:
- pyinstaller --onefile romulus.py
- bash <(curl -s https://codecov.io/bash)
deploy:
  provider: releases
  api_key:
    secure: AUTI2imohNYDwMzYdSLhEJDhg2mnLJpWslNhdO2R7ybmRpgmw0mDD4952DmkS+cWLc2y2SlKzcr/jcUOk8msyyNV4OFrbHzhfi3aX65LtApSct51xtgMf2Bh5KunreNDJzvHXxnKlxTXLaSPkL9jHcxoWzAeAqM9YwIZqeuGFi4rKcr027g7hjk4XuO3rHrPvRe5rNZ5Rtegmowx6zKwGtShMFjbcC5OHM1Qzh0O869ZYXEcD8KQV6frhNV7xcW3GQ8vKJaEXKrin8nkSfNF/yfDfAPHS0jMus/xI5VrCygrmi8YSORKYAEG1CedAYpoYQY58fW/QHmki6xNAM0QDnx3WIzGP8qo+IneKi5G/R64KJsO/wJJStWcm+UfYo7xtKBRrnjt57ZwEWTfvZtSTh+FCpFzp8KDmMxnHGNZTJohhwno0JsXI6Yu2gV1yISWfTfZl9odsgRjmxbRSvE7HkzNK2l1zxekLjkrAk00lO/XtxnOayUAcKpOm3s94gUu2vAzxfeqtNUN3Dis8XJQXZGH2KXxOvn3RGtrVp8VqCAv6lBAfFfUWSav0vdaMTIdPuLjyAgW3oXp/QBlU501xMSZLsOw889YONt8BV9eu+qFiNdEBZ8LiL8d+8YcPf3ozWTB9Whqj7cYzPqE6iUX4tBxWz8yqybmFFt8K7IR3PI=
  file: dist/romulus
  on:
    repo: ArthurMoore85/romulus
notifications:
  slack: arthurs-development:zBXY0Qtk68XSv168S8V5Ewub
