# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1042, 734)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.lblStatus = QtGui.QLabel(self.centralwidget)
        self.lblStatus.setObjectName(_fromUtf8("lblStatus"))
        self.gridLayout.addWidget(self.lblStatus, 2, 0, 1, 1)
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.label_3 = QtGui.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(10, 60, 991, 31))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.tableSearchResults = QtGui.QTableWidget(self.tab)
        self.tableSearchResults.setGeometry(QtCore.QRect(10, 90, 691, 491))
        self.tableSearchResults.setObjectName(_fromUtf8("tableSearchResults"))
        self.tableSearchResults.setColumnCount(0)
        self.tableSearchResults.setRowCount(0)
        self.line = QtGui.QFrame(self.tab)
        self.line.setGeometry(QtCore.QRect(710, 90, 20, 491))
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.frame = QtGui.QFrame(self.tab)
        self.frame.setGeometry(QtCore.QRect(790, 90, 171, 191))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.imgCoverSearch = QtGui.QLabel(self.frame)
        self.imgCoverSearch.setGeometry(QtCore.QRect(-1, -3, 171, 191))
        self.imgCoverSearch.setText(_fromUtf8(""))
        self.imgCoverSearch.setObjectName(_fromUtf8("imgCoverSearch"))
        self.lblSearchDescriptionSelected = QtGui.QLabel(self.tab)
        self.lblSearchDescriptionSelected.setGeometry(QtCore.QRect(740, 400, 261, 121))
        self.lblSearchDescriptionSelected.setText(_fromUtf8(""))
        self.lblSearchDescriptionSelected.setObjectName(_fromUtf8("lblSearchDescriptionSelected"))
        self.btnDownloadSelected = QtGui.QPushButton(self.tab)
        self.btnDownloadSelected.setGeometry(QtCore.QRect(740, 540, 271, 41))
        self.btnDownloadSelected.setObjectName(_fromUtf8("btnDownloadSelected"))
        self.layoutWidget = QtGui.QWidget(self.tab)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 991, 51))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label = QtGui.QLabel(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_3.addWidget(self.label)
        self.editSearchTitle = QtGui.QLineEdit(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.editSearchTitle.sizePolicy().hasHeightForWidth())
        self.editSearchTitle.setSizePolicy(sizePolicy)
        self.editSearchTitle.setObjectName(_fromUtf8("editSearchTitle"))
        self.horizontalLayout_3.addWidget(self.editSearchTitle)
        self.horizontalLayout_5.addLayout(self.horizontalLayout_3)
        self.btnSearch = QtGui.QPushButton(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnSearch.sizePolicy().hasHeightForWidth())
        self.btnSearch.setSizePolicy(sizePolicy)
        self.btnSearch.setObjectName(_fromUtf8("btnSearch"))
        self.horizontalLayout_5.addWidget(self.btnSearch)
        self.layoutWidget1 = QtGui.QWidget(self.tab)
        self.layoutWidget1.setGeometry(QtCore.QRect(740, 290, 271, 20))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_4 = QtGui.QLabel(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_6.addWidget(self.label_4)
        self.lblSearchTitleSelected = QtGui.QLabel(self.layoutWidget1)
        self.lblSearchTitleSelected.setText(_fromUtf8(""))
        self.lblSearchTitleSelected.setObjectName(_fromUtf8("lblSearchTitleSelected"))
        self.horizontalLayout_6.addWidget(self.lblSearchTitleSelected)
        self.layoutWidget2 = QtGui.QWidget(self.tab)
        self.layoutWidget2.setGeometry(QtCore.QRect(740, 320, 271, 20))
        self.layoutWidget2.setObjectName(_fromUtf8("layoutWidget2"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.label_5 = QtGui.QLabel(self.layoutWidget2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_7.addWidget(self.label_5)
        self.lblSearchYearSelected = QtGui.QLabel(self.layoutWidget2)
        self.lblSearchYearSelected.setText(_fromUtf8(""))
        self.lblSearchYearSelected.setObjectName(_fromUtf8("lblSearchYearSelected"))
        self.horizontalLayout_7.addWidget(self.lblSearchYearSelected)
        self.layoutWidget3 = QtGui.QWidget(self.tab)
        self.layoutWidget3.setGeometry(QtCore.QRect(740, 350, 271, 20))
        self.layoutWidget3.setObjectName(_fromUtf8("layoutWidget3"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout(self.layoutWidget3)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.label_6 = QtGui.QLabel(self.layoutWidget3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_8.addWidget(self.label_6)
        self.lblSearchPlatformSelected = QtGui.QLabel(self.layoutWidget3)
        self.lblSearchPlatformSelected.setText(_fromUtf8(""))
        self.lblSearchPlatformSelected.setObjectName(_fromUtf8("lblSearchPlatformSelected"))
        self.horizontalLayout_8.addWidget(self.lblSearchPlatformSelected)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.label_7 = QtGui.QLabel(self.tab_2)
        self.label_7.setGeometry(QtCore.QRect(20, 10, 291, 51))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.tableLocalCollection = QtGui.QTableWidget(self.tab_2)
        self.tableLocalCollection.setGeometry(QtCore.QRect(10, 60, 1001, 511))
        self.tableLocalCollection.setObjectName(_fromUtf8("tableLocalCollection"))
        self.tableLocalCollection.setColumnCount(0)
        self.tableLocalCollection.setRowCount(0)
        self.layoutWidget4 = QtGui.QWidget(self.tab_2)
        self.layoutWidget4.setGeometry(QtCore.QRect(560, 10, 441, 51))
        self.layoutWidget4.setObjectName(_fromUtf8("layoutWidget4"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.layoutWidget4)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_8 = QtGui.QLabel(self.layoutWidget4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout.addWidget(self.label_8)
        self.comboLocalFilter = QtGui.QComboBox(self.layoutWidget4)
        self.comboLocalFilter.setObjectName(_fromUtf8("comboLocalFilter"))
        self.horizontalLayout.addWidget(self.comboLocalFilter)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.label_2 = QtGui.QLabel(self.tab_3)
        self.label_2.setGeometry(QtCore.QRect(10, 10, 171, 41))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.tableActivity = QtGui.QTableWidget(self.tab_3)
        self.tableActivity.setGeometry(QtCore.QRect(10, 50, 1001, 192))
        self.tableActivity.setObjectName(_fromUtf8("tableActivity"))
        self.tableActivity.setColumnCount(0)
        self.tableActivity.setRowCount(0)
        self.label_9 = QtGui.QLabel(self.tab_3)
        self.label_9.setGeometry(QtCore.QRect(20, 280, 141, 31))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.tablePlayersLookup = QtGui.QTableWidget(self.tab_3)
        self.tablePlayersLookup.setGeometry(QtCore.QRect(20, 360, 981, 192))
        self.tablePlayersLookup.setObjectName(_fromUtf8("tablePlayersLookup"))
        self.tablePlayersLookup.setColumnCount(0)
        self.tablePlayersLookup.setRowCount(0)
        self.widget = QtGui.QWidget(self.tab_3)
        self.widget.setGeometry(QtCore.QRect(20, 310, 981, 34))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.widget)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_10 = QtGui.QLabel(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.horizontalLayout_2.addWidget(self.label_10)
        self.editFindGame = QtGui.QLineEdit(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.editFindGame.sizePolicy().hasHeightForWidth())
        self.editFindGame.setSizePolicy(sizePolicy)
        self.editFindGame.setObjectName(_fromUtf8("editFindGame"))
        self.horizontalLayout_2.addWidget(self.editFindGame)
        self.label_11 = QtGui.QLabel(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.horizontalLayout_2.addWidget(self.label_11)
        self.comboFindPlatform = QtGui.QComboBox(self.widget)
        self.comboFindPlatform.setObjectName(_fromUtf8("comboFindPlatform"))
        self.horizontalLayout_2.addWidget(self.comboFindPlatform)
        self.btnFindPlayers = QtGui.QPushButton(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnFindPlayers.sizePolicy().hasHeightForWidth())
        self.btnFindPlayers.setSizePolicy(sizePolicy)
        self.btnFindPlayers.setObjectName(_fromUtf8("btnFindPlayers"))
        self.horizontalLayout_2.addWidget(self.btnFindPlayers)
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.lblFriendsUsername = QtGui.QLabel(self.tab_4)
        self.lblFriendsUsername.setGeometry(QtCore.QRect(20, 10, 451, 41))
        self.lblFriendsUsername.setObjectName(_fromUtf8("lblFriendsUsername"))
        self.frame_2 = QtGui.QFrame(self.tab_4)
        self.frame_2.setGeometry(QtCore.QRect(840, 20, 171, 151))
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.lblPictureUser = QtGui.QLabel(self.frame_2)
        self.lblPictureUser.setGeometry(QtCore.QRect(-1, -3, 171, 161))
        self.lblPictureUser.setText(_fromUtf8(""))
        self.lblPictureUser.setObjectName(_fromUtf8("lblPictureUser"))
        self.tableFriendsList = QtGui.QTableWidget(self.tab_4)
        self.tableFriendsList.setGeometry(QtCore.QRect(10, 200, 561, 361))
        self.tableFriendsList.setObjectName(_fromUtf8("tableFriendsList"))
        self.tableFriendsList.setColumnCount(0)
        self.tableFriendsList.setRowCount(0)
        self.label_14 = QtGui.QLabel(self.tab_4)
        self.label_14.setGeometry(QtCore.QRect(20, 160, 121, 31))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.widget1 = QtGui.QWidget(self.tab_4)
        self.widget1.setGeometry(QtCore.QRect(20, 70, 301, 20))
        self.widget1.setObjectName(_fromUtf8("widget1"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.widget1)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_12 = QtGui.QLabel(self.widget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.horizontalLayout_4.addWidget(self.label_12)
        self.lblFriendsPoints = QtGui.QLabel(self.widget1)
        self.lblFriendsPoints.setObjectName(_fromUtf8("lblFriendsPoints"))
        self.horizontalLayout_4.addWidget(self.lblFriendsPoints)
        self.widget2 = QtGui.QWidget(self.tab_4)
        self.widget2.setGeometry(QtCore.QRect(20, 100, 301, 20))
        self.widget2.setObjectName(_fromUtf8("widget2"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout(self.widget2)
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.label_13 = QtGui.QLabel(self.widget2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_13.sizePolicy().hasHeightForWidth())
        self.label_13.setSizePolicy(sizePolicy)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.horizontalLayout_9.addWidget(self.label_13)
        self.lblFriendsLevel = QtGui.QLabel(self.widget2)
        self.lblFriendsLevel.setObjectName(_fromUtf8("lblFriendsLevel"))
        self.horizontalLayout_9.addWidget(self.lblFriendsLevel)
        self.tabWidget.addTab(self.tab_4, _fromUtf8(""))
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1042, 26))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuRetropie = QtGui.QMenu(self.menubar)
        self.menuRetropie.setObjectName(_fromUtf8("menuRetropie"))
        self.menuAbout = QtGui.QMenu(self.menubar)
        self.menuAbout.setObjectName(_fromUtf8("menuAbout"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionSettings = QtGui.QAction(MainWindow)
        self.actionSettings.setObjectName(_fromUtf8("actionSettings"))
        self.actionQuit = QtGui.QAction(MainWindow)
        self.actionQuit.setObjectName(_fromUtf8("actionQuit"))
        self.actionSync_Library = QtGui.QAction(MainWindow)
        self.actionSync_Library.setObjectName(_fromUtf8("actionSync_Library"))
        self.actionHelp = QtGui.QAction(MainWindow)
        self.actionHelp.setObjectName(_fromUtf8("actionHelp"))
        self.actionAbout_Romulus = QtGui.QAction(MainWindow)
        self.actionAbout_Romulus.setObjectName(_fromUtf8("actionAbout_Romulus"))
        self.menuFile.addAction(self.actionSettings)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menuRetropie.addAction(self.actionSync_Library)
        self.menuAbout.addAction(self.actionHelp)
        self.menuAbout.addAction(self.actionAbout_Romulus)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuRetropie.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Romulus", None))
        self.lblStatus.setText(_translate("MainWindow", "<h2>Status: Idle</h2>", None))
        self.label_3.setText(_translate("MainWindow", "<h3>Results:</h3>", None))
        self.btnDownloadSelected.setText(_translate("MainWindow", "Download", None))
        self.label.setText(_translate("MainWindow", "<h3>Title:</h3>", None))
        self.btnSearch.setText(_translate("MainWindow", "Search", None))
        self.btnSearch.setShortcut(_translate("MainWindow", "Return", None))
        self.label_4.setText(_translate("MainWindow", "<b>Title:</b>", None))
        self.label_5.setText(_translate("MainWindow", "<b>Year:</b>", None))
        self.label_6.setText(_translate("MainWindow", "<b>Platform:</b>", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "ROM Search", None))
        self.label_7.setText(_translate("MainWindow", "<h2>In your local collection:</h2>", None))
        self.label_8.setText(_translate("MainWindow", "<h3>Filter:</h3>", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Local Games Library", None))
        self.label_2.setText(_translate("MainWindow", "<h2>Current Activity</h2>", None))
        self.label_9.setText(_translate("MainWindow", "<h2>Find a player</h2>", None))
        self.label_10.setText(_translate("MainWindow", "Game:", None))
        self.label_11.setText(_translate("MainWindow", "Platform:", None))
        self.btnFindPlayers.setText(_translate("MainWindow", "Find Now", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Multipi World", None))
        self.lblFriendsUsername.setText(_translate("MainWindow", "<h2>USERNAME</h2>", None))
        self.label_14.setText(_translate("MainWindow", "<h2>Friends list</h2>", None))
        self.label_12.setText(_translate("MainWindow", "<b>Current points:</b>", None))
        self.lblFriendsPoints.setText(_translate("MainWindow", "0", None))
        self.label_13.setText(_translate("MainWindow", "<b>Current level:</b>", None))
        self.lblFriendsLevel.setText(_translate("MainWindow", "0", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "My Friends", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.menuRetropie.setTitle(_translate("MainWindow", "Retropie", None))
        self.menuAbout.setTitle(_translate("MainWindow", "About", None))
        self.actionSettings.setText(_translate("MainWindow", "Settings", None))
        self.actionQuit.setText(_translate("MainWindow", "Quit", None))
        self.actionSync_Library.setText(_translate("MainWindow", "Pi Control Center", None))
        self.actionHelp.setText(_translate("MainWindow", "Help", None))
        self.actionAbout_Romulus.setText(_translate("MainWindow", "About Romulus", None))

