# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'settingsWindow.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_settingsWindow(object):
    def setupUi(self, settingsWindow):
        settingsWindow.setObjectName(_fromUtf8("settingsWindow"))
        settingsWindow.resize(705, 542)
        self.centralwidget = QtGui.QWidget(settingsWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 701, 431))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.layoutWidget = QtGui.QWidget(self.tab)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 671, 61))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label = QtGui.QLabel(self.layoutWidget)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_2.addWidget(self.label)
        self.editDownloadLoc = QtGui.QLineEdit(self.layoutWidget)
        self.editDownloadLoc.setObjectName(_fromUtf8("editDownloadLoc"))
        self.horizontalLayout_2.addWidget(self.editDownloadLoc)
        self.btnDownloadLocBrowse = QtGui.QPushButton(self.layoutWidget)
        self.btnDownloadLocBrowse.setObjectName(_fromUtf8("btnDownloadLocBrowse"))
        self.horizontalLayout_2.addWidget(self.btnDownloadLocBrowse)
        self.layoutWidget1 = QtGui.QWidget(self.tab)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 90, 671, 61))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_3 = QtGui.QLabel(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_4.addWidget(self.label_3)
        self.comboRomSource = QtGui.QComboBox(self.layoutWidget1)
        self.comboRomSource.setObjectName(_fromUtf8("comboRomSource"))
        self.horizontalLayout_4.addWidget(self.comboRomSource)
        self.layoutWidget2 = QtGui.QWidget(self.tab)
        self.layoutWidget2.setGeometry(QtCore.QRect(10, 160, 181, 51))
        self.layoutWidget2.setObjectName(_fromUtf8("layoutWidget2"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_2 = QtGui.QLabel(self.layoutWidget2)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_3.addWidget(self.label_2)
        self.comboTheme = QtGui.QComboBox(self.layoutWidget2)
        self.comboTheme.setObjectName(_fromUtf8("comboTheme"))
        self.horizontalLayout_3.addWidget(self.comboTheme)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.btnFindRetropie = QtGui.QPushButton(self.tab_2)
        self.btnFindRetropie.setGeometry(QtCore.QRect(10, 10, 681, 41))
        self.btnFindRetropie.setObjectName(_fromUtf8("btnFindRetropie"))
        self.layoutWidget3 = QtGui.QWidget(self.tab_2)
        self.layoutWidget3.setGeometry(QtCore.QRect(10, 60, 681, 51))
        self.layoutWidget3.setObjectName(_fromUtf8("layoutWidget3"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.layoutWidget3)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_4 = QtGui.QLabel(self.layoutWidget3)
        self.label_4.setMinimumSize(QtCore.QSize(110, 0))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_5.addWidget(self.label_4)
        self.editPiIP = QtGui.QLineEdit(self.layoutWidget3)
        self.editPiIP.setObjectName(_fromUtf8("editPiIP"))
        self.horizontalLayout_5.addWidget(self.editPiIP)
        self.layoutWidget4 = QtGui.QWidget(self.tab_2)
        self.layoutWidget4.setGeometry(QtCore.QRect(10, 120, 681, 51))
        self.layoutWidget4.setObjectName(_fromUtf8("layoutWidget4"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.layoutWidget4)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_5 = QtGui.QLabel(self.layoutWidget4)
        self.label_5.setMinimumSize(QtCore.QSize(110, 0))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_6.addWidget(self.label_5)
        self.editPiUsername = QtGui.QLineEdit(self.layoutWidget4)
        self.editPiUsername.setObjectName(_fromUtf8("editPiUsername"))
        self.horizontalLayout_6.addWidget(self.editPiUsername)
        self.layoutWidget5 = QtGui.QWidget(self.tab_2)
        self.layoutWidget5.setGeometry(QtCore.QRect(10, 180, 681, 51))
        self.layoutWidget5.setObjectName(_fromUtf8("layoutWidget5"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.layoutWidget5)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.label_6 = QtGui.QLabel(self.layoutWidget5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setMinimumSize(QtCore.QSize(110, 0))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_7.addWidget(self.label_6)
        self.editPiPassword = QtGui.QLineEdit(self.layoutWidget5)
        self.editPiPassword.setObjectName(_fromUtf8("editPiPassword"))
        self.horizontalLayout_7.addWidget(self.editPiPassword)
        self.btnPiViewPassword = QtGui.QPushButton(self.layoutWidget5)
        self.btnPiViewPassword.setObjectName(_fromUtf8("btnPiViewPassword"))
        self.horizontalLayout_7.addWidget(self.btnPiViewPassword)
        self.layoutWidget6 = QtGui.QWidget(self.tab_2)
        self.layoutWidget6.setGeometry(QtCore.QRect(10, 300, 661, 81))
        self.layoutWidget6.setObjectName(_fromUtf8("layoutWidget6"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout(self.layoutWidget6)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.label_7 = QtGui.QLabel(self.layoutWidget6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_8.addWidget(self.label_7)
        self.lblPiStatus = QtGui.QLabel(self.layoutWidget6)
        self.lblPiStatus.setObjectName(_fromUtf8("lblPiStatus"))
        self.horizontalLayout_8.addWidget(self.lblPiStatus)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.layoutWidget7 = QtGui.QWidget(self.centralwidget)
        self.layoutWidget7.setGeometry(QtCore.QRect(480, 440, 221, 51))
        self.layoutWidget7.setObjectName(_fromUtf8("layoutWidget7"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.layoutWidget7)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.btnCancel = QtGui.QPushButton(self.layoutWidget7)
        self.btnCancel.setObjectName(_fromUtf8("btnCancel"))
        self.horizontalLayout.addWidget(self.btnCancel)
        self.btnSave = QtGui.QPushButton(self.layoutWidget7)
        self.btnSave.setObjectName(_fromUtf8("btnSave"))
        self.horizontalLayout.addWidget(self.btnSave)
        settingsWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(settingsWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 705, 26))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        settingsWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(settingsWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        settingsWindow.setStatusBar(self.statusbar)

        self.retranslateUi(settingsWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(settingsWindow)

    def retranslateUi(self, settingsWindow):
        settingsWindow.setWindowTitle(_translate("settingsWindow", "Settings", None))
        self.label.setText(_translate("settingsWindow", "Download location:", None))
        self.btnDownloadLocBrowse.setText(_translate("settingsWindow", "Browse", None))
        self.label_3.setText(_translate("settingsWindow", "ROM Source:", None))
        self.label_2.setText(_translate("settingsWindow", "Theme:", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("settingsWindow", "General Settings", None))
        self.btnFindRetropie.setText(_translate("settingsWindow", "Try and find my Retropie!", None))
        self.label_4.setText(_translate("settingsWindow", "Last know IP:", None))
        self.label_5.setText(_translate("settingsWindow", "Username:", None))
        self.label_6.setText(_translate("settingsWindow", "Password", None))
        self.btnPiViewPassword.setText(_translate("settingsWindow", "View/Edit Password", None))
        self.label_7.setText(_translate("settingsWindow", "<h2>Current Pi status:</h2>", None))
        self.lblPiStatus.setText(_translate("settingsWindow", "<h2>Offline</h2>", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("settingsWindow", "Retropie Settings", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("settingsWindow", "Plugins", None))
        self.btnCancel.setText(_translate("settingsWindow", "Cancel", None))
        self.btnSave.setText(_translate("settingsWindow", "Save and Close", None))

